DROP TABLE IF EXISTS public.inventory;
DROP TABLE IF EXISTS public.classification;

CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHAR(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9, 0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification
        FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

INSERT INTO public.classification (classification_name) VALUES
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

INSERT INTO public.inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id) VALUES
    ('Ford', 'Mustang', '2022', 'Deportivo de alto rendimiento', 'mustang.jpg', 'mustang_thumb.jpg', 45000, 10000, 'Rojo', 2),
    ('Toyota', 'Camry', '2021', 'Sedán familiar', 'camry.jpg', 'camry_thumb.jpg', 30000, 20000, 'Azul', 5),
    ('Chevrolet', 'Tahoe', '2020', 'SUV espacioso y cómodo', 'tahoe.jpg', 'tahoe_thumb.jpg', 55000, 15000, 'Negro', 3),
    ('RAM', '1500', '2019', 'Camioneta de carga pesada', 'ram.jpg', 'ram_thumb.jpg', 40000, 25000, 'Blanco', 4),
    ('Honda', 'Civic', '2023', 'Sedán económico y confiable', 'civic.jpg', 'civic_thumb.jpg', 28000, 5000, 'Plata', 5);

SELECT * FROM public.classification;
SELECT * FROM public.inventory;

SELECT i.inv_id, i.inv_make, i.inv_model, c.classification_name
FROM public.inventory AS i
JOIN public.classification AS c ON i.classification_id = c.classification_id;


INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id
) VALUES (
    'Nissan', 'Sentra', '2022', 'Compacto económico y eficiente', 'sentra.jpg', 'sentra_thumb.jpg', 25000, 12000, 'Gris', 5
);

UPDATE public.inventory
SET inv_price = 31000
WHERE inv_make = 'Toyota' AND inv_model = 'Camry';

DELETE FROM public.inventory
WHERE inv_make = 'RAM' AND inv_model = '1500';


Select * from public.inventory

------------------------------------

INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

UPDATE public.account
SET account_type = 'Admin'
WHERE account_email = 'tony@starkent.com';

DELETE FROM public.account
WHERE account_email = 'tony@starkent.com';

UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_model = 'Hummer';

SELECT i.inv_make, i.inv_model, c.classification_name
FROM public.inventory AS i
JOIN public.classification AS c ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

---------------------------------------------------------------------------
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_model = 'Hummer';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');



